%% Hash table mapping

function filenames = get_filename_list( type )
    switch type 

      case 'resurface'
        filenames = { ...
            'subject1-1.txt',...
            'subject7-R1.txt',...
            'subject9-L1.txt',...
            'subject9-R1.txt',...
            'subject10-L1.txt',...
            'subject10-R1.txt'};
        
      case 'non-resurface'
        filenames = { ...
            'subject3-R1.txt',...
            'subject4-R1.txt',...
            'subject6-L1.txt',...
            'subject6-R1.txt',...
            'subject7-L1.txt',...
            'subject8-R1.txt'};

      case 'subject-6'
        filenames = { ...
            'subject6-L1.txt',...
            'subject6-L3-FreeFall.txt',...
            'subject6-R1.txt',...
            'subject6-R3-FreeFall.txt',...
            'subject6-R4-Lay-Assist.txt',...
            'subject6-R5-Lay-Self.txt'};

      case 'has-sound'
        filenames = { ...
            'subject1-1.txt',...
            'subject1-2.txt',...
            'subject4-R1.txt',...
            'subject4-R2.txt',...
            'subject6-R4-Lay-Assist.txt',...
            'subject6-R5-Lay-Self.txt'};
    end
end
