#!/usr/bin/python

from pyeemd import eemd
from pyeemd.utils import plot_imfs

import numpy as np
import sys
import re

from os import listdir, makedirs
from os.path import isfile, join, exists

in_path = sys.argv[1]
out_dir = sys.argv[2]

print 'reading: {0}'.format(in_path)
print 'output directory: {0}'.format(out_dir)
# now at progress/emd
# in_dir = "../../data/txt_data/"
# filenames = [ file for file in listdir(in_dir) if file.endswith("txt")]
# out_dir = "../../data/imfs/{0}/".format(filenames[10].replace('.txt',''))
knee = np.loadtxt( in_path, delimiter='\n')

if not exists(out_dir):
    print 'output directory doesn\'t exist make {0}'.format(out_dir)
    makedirs(out_dir)

print 'running eemd'
imfs = eemd( knee, ensemble_size=50, num_siftings=10)
imfsAndRaw = np.vstack(( knee, imfs ))

for i, x in enumerate( imfsAndRaw ):
    print 'saving eemd #{0}'.format(i)
    np.savetxt( out_dir + '/' + str(i) + '.txt', x, delimiter='\n')

# print 'saving eemd'
# np.savetxt( out_dir + filenames[10] , imfsAndRaw, delimiter=',')

print 'finish'
