#!/usr/bin/python
import numpy as np
import sys
from natsort import natsorted, ns

from os import listdir , makedirs
from os.path import isfile, isdir, join, exists

# EDIT HERE
def isPass(alpha):
    criterion = 0.5
    # return alpha > criterion    
    return alpha < criterion

def ensure_directory(direc):
    return direc if direc.endswith('/') else direc + '/'

imfs_dir = ensure_directory(sys.argv[1])
dfa_pair_dir = ensure_directory(sys.argv[2])
alpha_dir = ensure_directory(sys.argv[3])
signal_after_dfa_dir = ensure_directory(sys.argv[4])

# MAKEDIR if not exists
for out_dir_to_check in [ dfa_pair_dir, alpha_dir, signal_after_dfa_dir ]:
    if not exists( out_dir_to_check ):
        print 'directory doesn\'t exist make {0}'.format( out_dir_to_check )
        makedirs( out_dir_to_check )


# dir will cause a name crash
direcs = [ direc for direc in listdir(dfa_pair_dir) if isdir(join(dfa_pair_dir,direc)) ]

for direc in direcs:
    
    in_dir = dfa_pair_dir + '/' + direc + '/'

    filenames = [ file for file in listdir(in_dir) if file.endswith("txt") and not file.startswith("0") ]
    filenames = natsorted( filenames, key=lambda y: y.lower() )
    filenames = natsorted( filenames, alg=ns.IGNORECASE )
    # mutated it

    print '===> filenames are:'
    print filenames

    alpha_list = ""
    threshold = 0.5
    qualified_imfs_list = []

    for f in filenames[:-1]:
        print 'accumulating: ' + in_dir + f
        s, F = np.genfromtxt( in_dir + f, unpack=True)
        alpha = np.polyfit( s, F, 1 )[0]
        alpha_list += "{0},{1}\n".format( f.replace('.txt',''), alpha )

        if( isPass(alpha) ):
            qualified_imfs_list.append(f)


    # OUTPUTING

    print 'write to ' + alpha_dir + direc + '-alpha.txt'


    f = open( alpha_dir + direc + '-alpha.txt', 'w')
    f.closed
    f.write(alpha_list)

    pretty_list = [ l.replace('.txt','') for l in qualified_imfs_list ]
    pretty_list.sort( key=int ) # mutated
    print 'qualified imfs are: ' + ', '.join(pretty_list)

    for i, f in enumerate(qualified_imfs_list):
        if i==0:
            out_signal = np.loadtxt( imfs_dir + '/' + direc + '/' + f )
        else :
            out_signal += np.loadtxt( imfs_dir + direc + '/' + f )


    print 'write to ' + signal_after_dfa_dir + direc + '.dfa.txt'
    np.savetxt( signal_after_dfa_dir + direc + '.dfa.txt', out_signal )
